apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: privileged
  name: provider-aws
spec:
  deployment:
    extension:
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: aws
  - kind: BackupEntry
    type: aws
  - kind: Bastion
    type: aws
  - kind: ControlPlane
    type: aws
  - kind: DNSRecord
    type: aws-route53
  - kind: Infrastructure
    type: aws
  - kind: Worker
    type: aws
