apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: provider-openstack
spec:
  deployment:
    extension:
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: openstack
  - kind: BackupEntry
    type: openstack
  - kind: Bastion
    type: openstack
  - kind: ControlPlane
    type: openstack
  - kind: DNSRecord
    type: openstack-designate
  - kind: Infrastructure
    type: openstack
  - kind: Worker
    type: openstack
