apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-aws
spec:
  deployment:
    admission:
      values: {}
#       resources:
#         requests:
#           cpu: 50m
#           memory: 100Mi
    extension:
      values: {}
#       resources:
#         requests:
#           cpu: 100m
#           memory: 512Mi
