apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-aws
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionAwsRuntime.helmChart.ref }}
      {{- if .resources.admissionAwsRuntime.helmChart.imageMap }}
      values:
{{ toIndentYAML 2 .resources.admissionAwsRuntime.helmChart.imageMap.gardenerExtensionAdmissionAws | indent 8 }}
      {{- end }}
      virtualCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionAwsApplication.helmChart.ref }}
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.providerAws.helmChart.ref }}
      {{- if (or .resources.providerAws.helmChart.imageMap .imageVectorOverwrite) }}
      runtimeClusterValues:
        {{- if .resources.providerAws.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerAws.helmChart.imageMap.gardenerExtensionProviderAws | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
      {{- if (or .resources.providerAws.helmChart.imageMap .imageVectorOverwrite) }}
      values:
        {{- if .resources.providerAws.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerAws.helmChart.imageMap.gardenerExtensionProviderAws | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
