apiVersion: landscape.config.gardener.cloud/v1alpha1
kind: LandscapeKitConfiguration
# ocm:
#   repositories:
#   - <repo-url>
#   rootComponent:
#     name: <component-name>
#     version: <component-version>
#   originalRefs: true
#   ignoreMissingComponents: false
# repositories:
#   base:
#     target: ./
#     componentsYamlOverrides:
#     - overrides/base-extras.yaml
#   landscape:
#     url: https://github.com/<org>/<repo>
#     ref:
#       branch: <branch-name>
#     baseLink: ./base
#     target: ./
#     componentsYamlOverrides:
#     - overrides/landscape-extras.yaml
# components:
#   exclude:
#   - component-name
# versionConfig:
#   defaultVersionsUpdateStrategy: ReleaseBranch
#   checkMode: Strict # or Warning
# mergeMode: Hint
