// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package version

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/spf13/afero"
	"k8s.io/component-base/version"
)

const (
	// MetaDirName is the name of the metadata directory within .glk
	MetaDirName = "meta"
	// VersionFileName is the name of the version metadata file
	VersionFileName = "version.json"
)

// Info contains version information for a generated base
type Info struct {
	Version    string `json:"version"`
	GitVersion string `json:"gitVersion"`
	GitCommit  string `json:"gitCommit"`
	BuildDate  string `json:"buildDate"`
	Major      string `json:"major"`
	Minor      string `json:"minor"`
}

// WriteVersionMetadata writes the current version information to .glk/meta/version.json
func WriteVersionMetadata(targetPath string, fs afero.Afero) error {
	versionInfo := version.Get()

	metadata := Info{
		Version:    versionInfo.GitVersion,
		GitVersion: versionInfo.GitVersion,
		GitCommit:  versionInfo.GitCommit,
		BuildDate:  versionInfo.BuildDate,
		Major:      versionInfo.Major,
		Minor:      versionInfo.Minor,
	}

	metaDir := filepath.Join(targetPath, ".glk", MetaDirName)
	if err := fs.MkdirAll(metaDir, 0744); err != nil {
		return fmt.Errorf("failed to create metadata directory: %w", err)
	}

	versionFilePath := filepath.Join(metaDir, VersionFileName)
	data, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal version metadata: %w", err)
	}

	if err := fs.WriteFile(versionFilePath, data, 0644); err != nil {
		return fmt.Errorf("failed to write version metadata: %w", err)
	}

	return nil
}

// ReadVersionMetadata reads the version information from .glk/meta/version.json
func ReadVersionMetadata(targetPath string, fs afero.Afero) (*Info, error) {
	versionFilePath := filepath.Join(targetPath, ".glk", MetaDirName, VersionFileName)

	exists, err := fs.Exists(versionFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to check version file existence: %w", err)
	}

	if !exists {
		return nil, fmt.Errorf("base directory was generated by an older version of gardener-landscape-kit that did not track version information. Please regenerate the base directory with the current version")
	}

	data, err := fs.ReadFile(versionFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read version metadata: %w", err)
	}

	var metadata Info
	if err := json.Unmarshal(data, &metadata); err != nil {
		return nil, fmt.Errorf("failed to parse version metadata: %w", err)
	}

	return &metadata, nil
}

// sanitizeVersion removes invalid semver characters from version strings.
// Handles special development versions like "v0.0.0-master+$Format:%H$".
func sanitizeVersion(v string) string {
	// Remove anything after '+' (build metadata with invalid characters)
	if idx := strings.Index(v, "+"); idx != -1 {
		v = v[:idx]
	}
	return v
}

// ValidateVersionCompatibility checks if the landscape version is compatible with the base version.
// Returns an error if landscapeVersion > baseVersion.
func ValidateVersionCompatibility(baseVersion, landscapeVersion string) error {
	// Sanitize versions before parsing
	baseVersion = sanitizeVersion(baseVersion)
	landscapeVersion = sanitizeVersion(landscapeVersion)

	baseVer, err := semver.NewVersion(baseVersion)
	if err != nil {
		return fmt.Errorf("failed to parse base version %q: %w", baseVersion, err)
	}

	landscapeVer, err := semver.NewVersion(landscapeVersion)
	if err != nil {
		return fmt.Errorf("failed to parse landscape version %q: %w", landscapeVersion, err)
	}

	// Allow landscape generation if landscapeVersion <= baseVersion
	if landscapeVer.GreaterThan(baseVer) {
		return fmt.Errorf("landscape generation version (%s) is newer than base generation version (%s). Please regenerate the base directory using the current version of gardener-landscape-kit, or downgrade your gardener-landscape-kit installation to %s or earlier", landscapeVersion, baseVersion, baseVersion)
	}

	return nil
}

// ValidateLandscapeVersionCompatibility performs end-to-end version compatibility validation
// by reading the base version from metadata and comparing it with the current tool version.
func ValidateLandscapeVersionCompatibility(targetPath string, fs afero.Afero) error {
	baseMetadata, err := ReadVersionMetadata(targetPath, fs)
	if err != nil {
		return err
	}

	return ValidateVersionCompatibility(baseMetadata.Version, version.Get().GitVersion)
}
