//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LandscapeKitConfiguration) DeepCopyInto(out *LandscapeKitConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LandscapeKitConfiguration.
func (in *LandscapeKitConfiguration) DeepCopy() *LandscapeKitConfiguration {
	if in == nil {
		return nil
	}
	out := new(LandscapeKitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LandscapeKitConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMComponent) DeepCopyInto(out *OCMComponent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMComponent.
func (in *OCMComponent) DeepCopy() *OCMComponent {
	if in == nil {
		return nil
	}
	out := new(OCMComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMConfig) DeepCopyInto(out *OCMConfig) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.RootComponent = in.RootComponent
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMConfig.
func (in *OCMConfig) DeepCopy() *OCMConfig {
	if in == nil {
		return nil
	}
	out := new(OCMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMConfiguration) DeepCopyInto(out *OCMConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.OCMConfig != nil {
		in, out := &in.OCMConfig, &out.OCMConfig
		*out = new(OCMConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMConfiguration.
func (in *OCMConfiguration) DeepCopy() *OCMConfiguration {
	if in == nil {
		return nil
	}
	out := new(OCMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCMConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
