apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-azure
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionAzureRuntime.helmChart.ref }}
      {{- if .resources.admissionAzureRuntime.helmChart.imageMap }}
      values:
{{ toIndentYAML 2 .resources.admissionAzureRuntime.helmChart.imageMap.gardenerExtensionAdmissionAzure | indent 8 }}
      {{- end }}
      virtualCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionAzureApplication.helmChart.ref }}
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.providerAzure.helmChart.ref }}
      {{- if (or .resources.providerAzure.helmChart.imageMap .imageVectorOverwrite) }}
      runtimeClusterValues:
        {{- if .resources.providerAzure.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerAzure.helmChart.imageMap.gardenerExtensionProviderAzure | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
      {{- if (or .resources.providerAzure.helmChart.imageMap .imageVectorOverwrite) }}
      values:
        {{- if .resources.providerAzure.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerAzure.helmChart.imageMap.gardenerExtensionProviderAzure | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
