apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: os-suse-chost
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.osSuseChost.helmChart.ref }}
      values:
        {{- if .resources.osSuseChost.helmchartImagemap }}
{{ indent 8 (toIndentYAML 2 .resources.osSuseChost.helmchartImagemap.gardenerExtensionOsSuseChost) }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
