apiVersion: landscape.config.gardener.cloud/v1alpha1
kind: LandscapeKitConfiguration
# ocm:
#   repositories:
#   - <repo-url>
#   rootComponent:
#     name: <component-name>
#     version: <component-version>
#   originalRefs: true
repositories:
  base:
    componentsFiles:
    - components.yaml
  landscape:
    url: http://gitops:testtest@git.local.gardener.cloud:6080/gitops/test-landscape.git
    ref:
      branch: main
    baseLink: ./base
components:
  include:
  - flux
  - github
# TODO(timuthy): Remove this config once dev versions are ignored.
versionConfig:
  checkMode: Warning
