#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

function camelCase {
  # Remove the 'github.com' prefix and any following separators
  sed -r 's/^github\.com[\/\.:\-]*//' <<< "$1" |
  # Capitalize the letter following any separator (/, ., :, -)
  sed -r 's/[\/\.:\-]([a-zA-Z])/\U\1/g' |
  # Remove any remaining separators
  sed -r 's/[\/\.:\-]//g' |
  # Capitalize the first letter if it's lowercase
  sed -r 's/^[a-z]/\U&/'
}

package_name="${1:-componentvector}"
components_yaml="${2:-components.yaml}"
constant_prefix="${3:-}"

out="
$(cat "$(dirname $0)/LICENSE_BOILERPLATE.txt")

// Code generated by $(basename $0). DO NOT EDIT.

package $package_name

const ("

for component_name in $(yq -r '[.components[].name] | sort | unique | .[]' $components_yaml); do
  variable_name="$(camelCase "$component_name")"

  out="
$out
	// ${constant_prefix}Name${variable_name} is a constant for a component in the component vector with name '$component_name'.
	${constant_prefix}Name${variable_name} = \"$component_name\""
done

out="
$out
)
"

out_file="${components_yaml%.yaml}.go"
echo "$out" > "$out_file"
goimports -l -w "$out_file"
