apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    kubernetes.io/metadata.name: flux-system
    networking.gardener.cloud/access-target-apiserver: allowed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        networking.resources.gardener.cloud/to-garden-virtual-garden-kube-apiserver-tcp-443: allowed
