// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-componentname-constants.sh. DO NOT EDIT.

package componentvector

const (
	// NameGardenerGardener is a constant for a component in the component vector with name 'github.com/gardener/gardener'.
	NameGardenerGardener = "github.com/gardener/gardener"
)
