// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-componentname-constants.sh. DO NOT EDIT.

package componentvector

const (
	// NameGardenerGardener is a constant for a component in the component vector with name 'github.com/gardener/gardener'.
	NameGardenerGardener = "github.com/gardener/gardener"
	// NameGardenerGardenerExtensionNetworkingCalico is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-networking-calico'.
	NameGardenerGardenerExtensionNetworkingCalico = "github.com/gardener/gardener-extension-networking-calico"
	// NameGardenerGardenerExtensionNetworkingCilium is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-networking-cilium'.
	NameGardenerGardenerExtensionNetworkingCilium = "github.com/gardener/gardener-extension-networking-cilium"
	// NameGardenerGardenerExtensionOsGardenlinux is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-os-gardenlinux'.
	NameGardenerGardenerExtensionOsGardenlinux = "github.com/gardener/gardener-extension-os-gardenlinux"
	// NameGardenerGardenerExtensionOsSuseChost is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-os-suse-chost'.
	NameGardenerGardenerExtensionOsSuseChost = "github.com/gardener/gardener-extension-os-suse-chost"
	// NameGardenerGardenerExtensionProviderAws is a constant for a component in the component vector with name 'github.com/gardener/gardener-extension-provider-aws'.
	NameGardenerGardenerExtensionProviderAws = "github.com/gardener/gardener-extension-provider-aws"
)
