apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: shoot-access-virtual-garden-flux
  namespace: garden
  labels:
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    serviceaccount.resources.gardener.cloud/name: flux
    serviceaccount.resources.gardener.cloud/namespace: kube-system
    serviceaccount.resources.gardener.cloud/token-expiration-duration: 3h
    serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://virtual-garden-kube-apiserver.garden.svc.cluster.local
      name: garden
    contexts:
    - context:
        cluster: garden
        user: garden
        namespace: garden
      name: garden
    current-context: garden
    users:
    - name: garden
---
apiVersion: resources.gardener.cloud/v1alpha1
kind: ManagedResource
metadata:
  name: virtual-garden-access-flux
  namespace: garden
spec:
  secretRefs:
  - name: managedresource-virtual-garden-access-flux
---
apiVersion: v1
kind: Secret
metadata:
  name: managedresource-virtual-garden-access-flux
  namespace: garden
type: Opaque
stringData:
  clusterrolebinding____gardener.cloud.virtual-garden-access-flux.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: gardener.cloud.sap:virtual-garden-flux
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: flux
      namespace: kube-system
