---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: <branch_name> # This value needs to be modified by the user
  secretRef:
    name: flux-system
  url: https://github.com/<org>/<repo> # This value needs to be modified by the user
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: <landscape path within landscape repo, e.g. ./flux> # This value needs to be modified by the user
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
