apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gardener-operator
  namespace: garden
spec:
  interval: 10m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: {{ .tag }}
  url: oci://{{ .repository }}
