apiVersion: operator.gardener.cloud/v1alpha1
kind: Garden
metadata:
  name: garden
spec:
# extensions:
  runtimeCluster:
#   ingress:
    settings:
      topologyAwareRouting:
        enabled: false
      verticalPodAutoscaler:
        enabled: true
  virtualCluster:
    etcd:
      events:
        storage:
          capacity: 10Gi
      main:
        storage:
          capacity: 25Gi
    gardener:
#     gardenerAPIServer:
#       featureGates:
#         CloudProfileCapabilities: true
#         InPlaceNodeUpdates: true
      gardenerDashboard:
        enableTokenLogin: true
        logLevel: info
    kubernetes:
      kubeAPIServer:
        eventTTL: 1h0m0s
        logging:
          verbosity: 2
        requests:
          maxMutatingInflight: 200
          maxNonMutatingInflight: 400
      kubeControllerManager:
        certificateSigningDuration: 48h0m0s
      version: 1.33.6
    maintenance:
      timeWindow:
        begin: 220000+0100
        end: 230000+0100
