apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-openstack
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionOpenstackRuntime.helmChart.ref }}
      {{- if .resources.admissionOpenstackRuntime.helmChart.imageMap }}
      values:
{{ toIndentYAML 2 .resources.admissionOpenstackRuntime.helmChart.imageMap.gardenerExtensionAdmissionOpenstack | indent 8 }}
      {{- end }}
      virtualCluster:
        helm:
          ociRepository:
            ref: {{ .resources.admissionOpenstackApplication.helmChart.ref }}
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.providerOpenstack.helmChart.ref }}
      {{- if (or .resources.providerOpenstack.helmChart.imageMap .imageVectorOverwrite) }}
      runtimeClusterValues:
        {{- if .resources.providerOpenstack.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerOpenstack.helmChart.imageMap.gardenerExtensionProviderOpenstack | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
      {{- if (or .resources.providerOpenstack.helmChart.imageMap .imageVectorOverwrite) }}
      values:
        {{- if .resources.providerOpenstack.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.providerOpenstack.helmChart.imageMap.gardenerExtensionProviderOpenstack | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- end }}
