apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: os-gardenlinux
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.osGardenlinux.helmChart.ref }}
      values:
        {{- if .resources.osGardenlinux.helmchartImagemap }}
{{ indent 8 (toIndentYAML 2 .resources.osGardenlinux.helmchartImagemap.gardenerExtensionOsGardenlinux) }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
