// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package kustomization

import (
	"maps"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/afero"
	kustomize "sigs.k8s.io/kustomize/api/types"
	"sigs.k8s.io/yaml"

	"github.com/gardener/gardener-landscape-kit/pkg/components"
	"github.com/gardener/gardener-landscape-kit/pkg/utils/files"
)

const (
	// KustomizationFileName is the name of the component Kustomization file.
	KustomizationFileName = "kustomization.yaml"

	// FluxKustomizationFileName is the name of the Flux Kustomization file.
	FluxKustomizationFileName = "flux-kustomization.yaml"

	// FluxSystemRepositoryName is the name of the Flux system repository.
	FluxSystemRepositoryName = "flux-system"

	// OverrideDir is the directory referenced by the Flux Kustomization of a component.
	OverrideDir = "resources"

	autoGenerationNotice = "# This file is auto-generated by the gardener-landscape-kit. Do not edit manually.\n"
)

// NewKustomization creates a Kustomization with the given resources.
func NewKustomization(resources []string, patches []kustomize.Patch) *kustomize.Kustomization {
	return &kustomize.Kustomization{
		TypeMeta: kustomize.TypeMeta{
			APIVersion: kustomize.KustomizationVersion,
			Kind:       kustomize.KustomizationKind,
		},
		Resources: resources,
		Patches:   patches,
	}
}

// WriteKustomizationComponent writes the objects and a Kustomization file to the fs.
// The Kustomization file references all other objects.
// The objects map will be modified to include the Kustomization file.
func WriteKustomizationComponent(objects map[string][]byte, baseDir, componentDir string, fs afero.Afero) error {
	kustomization := NewKustomization(slices.Collect(maps.Keys(objects)), nil)
	content, err := yaml.Marshal(kustomization)
	if err != nil {
		return err
	}
	objects[KustomizationFileName] = content
	return files.WriteObjectsToFilesystem(objects, baseDir, componentDir, fs)
}

// WriteLandscapeComponentsKustomizations traverses through the generated components directory and adds
// Kustomize kustomization.yaml files for each level until each component leaf node containing a Flux Kustomization is reached.
func WriteLandscapeComponentsKustomizations(options components.Options) error {
	fs := options.GetFilesystem()
	targetDir := path.Clean(options.GetTargetPath())
	componentsDir := filepath.Join(targetDir, components.DirName)

	return fs.Walk(componentsDir, writeKustomizationsToFileTree(fs, targetDir))
}

func writeKustomizationsToFileTree(fs afero.Afero, targetDir string) func(dir string, info os.FileInfo, err error) error {
	var completedPaths []string

	return func(dir string, info os.FileInfo, err error) error {
		if err != nil || !info.IsDir() {
			return err
		}

		for _, p := range completedPaths {
			if isCompleted, err := path.Match(p, dir); err != nil || isCompleted {
				return err
			}
		}

		exists, err := fs.Exists(path.Join(dir, FluxKustomizationFileName))
		if err != nil {
			return err
		}
		if exists {
			completedPaths = append(completedPaths, dir+"/*")
			return nil
		}

		subDirs, err := fs.ReadDir(dir)
		if err != nil {
			return err
		}
		var directories []string
		for _, subDir := range subDirs {
			if subDir.IsDir() {
				exists, err := fs.Exists(path.Join(dir, subDir.Name(), FluxKustomizationFileName))
				if err != nil {
					return err
				}
				if exists {
					directories = append(directories, path.Join(subDir.Name(), FluxKustomizationFileName))
					completedPaths = append(completedPaths, path.Join(dir, subDir.Name(), "*"))
				} else {
					directories = append(directories, subDir.Name())
				}
			}
		}

		relativePath, _ := strings.CutPrefix(dir, targetDir)
		return writeKustomizationFile(fs, targetDir, relativePath, directories)
	}
}

func writeKustomizationFile(fs afero.Afero, landscapeDir, relativePath string, directories []string) error {
	var (
		err     error
		objects = make(map[string][]byte)
	)

	objects[KustomizationFileName], err = yaml.Marshal(NewKustomization(directories, nil))
	if err != nil {
		return err
	}

	objects[KustomizationFileName] = append([]byte(autoGenerationNotice), objects[KustomizationFileName]...)

	return files.WriteObjectsToFilesystem(objects, landscapeDir, relativePath, fs)
}
