apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: os-gardenlinux
spec:
  deployment:
    extension:
      values: {}
  resources:
  - kind: OperatingSystemConfig
    type: gardenlinux
  - kind: OperatingSystemConfig
    type: gardenlinux-fips
  - kind: OperatingSystemConfig
    type: memoryone-gardenlinux
