apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: shoot-networking-problemdetector
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.shootNetworkingProblemdetector.helmChart.ref }}
      {{- if (or .resources.shootNetworkingProblemdetector.helmChart.imageMap .imageVectorOverwrite) }}
      values:
        {{- if .resources.shootNetworkingProblemdetector.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.shootNetworkingProblemdetector.helmChart.imageMap.gardenerExtensionShootNetworkingProblemdetector | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- else }}
#     values:
      {{- end }}
#       controllers:
#         healthcheck:
#           concurrentSyncs: 10
#         lifecycle:
#           concurrentSyncs: 10
#       networkProblemDetector:
#         k8sExporter:
#           enabled: true
#       replicaCount: 1
