apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: runtime-gvisor
spec:
  deployment:
    extension:
      values: {}
#       resources:
#         requests:
#           cpu: 100m
#           memory: 64Mi
