apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: runtime-gvisor
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: {{ .resources.runtimeGvisor.helmChart.ref }}
      {{- if (or .resources.runtimeGvisor.helmChart.imageMap .imageVectorOverwrite) }}
      values:
        {{- if .resources.runtimeGvisor.helmChart.imageMap }}
{{ toIndentYAML 2 .resources.runtimeGvisor.helmChart.imageMap.gardenerExtensionRuntimeGvisor | indent 8 }}
        {{- end }}
        {{- if .imageVectorOverwrite }}
        imageVectorOverwrite: |
{{ indent 10 .imageVectorOverwrite }}
        {{- end }}
      {{- else }}
#     values:
      {{- end }}
#       resources:
#         requests:
#           cpu: 100m
#           memory: 64Mi
